### ISSUE TITLE
DELETE /item/<id>

### ISSUE THREAD

**Issue by raq929** [leahvelleman/sabelotodo#4]
A DELETE request to /item/1 should delete the item with ID 1
If the ID does not exist in the database, this route should return 404

Test with curl or postman

Bonus: Write automated tests using pytest

**Comment by leahvelleman** [comment]
> A DELETE request to /item/1 should get the item with ID 1
Should this be "delete the item"?

What status code should result from a successful deletion?

What status code should result in the event that the ID exists but the deletion fails for some other reason? (Not sure this can happen in the current setup...)

If the items look like this:
```
id | name | order
---+------+------
123| a    | 1
748| b    | 2

Should any JSON or HTML be returned by a successful deletion?

**Comment by raq929** [comment]
Successful delete should return 200 with no body.
If the deletion fails internally, I think we want a 500 error, which I think is what will happen if the server errors in the middle. 
The question about order is a good one, let me think on it a bit. I suspect I will conclude that we can just leave missing order numbers and it'll be fine.

**Comment by raq929** [comment]
I'm doing some research and consulting on ordering, but for delete, definitely just delete the item and leave a gap. :)
